==== HPWM 10 Bit

*Syntax:*
[subs="specialcharacters,quotes"]
----
    HPWM _channel, frequency, duty cycle, timer_
----
*Command Availability:*

Only available on Microchip PIC microcontrollers with the PWM module.

For the Capture/Compare/PWM (CCP) module, see here <<_hpwm_ccp,HPWM CCP>>

*Explanation:*

This command sets up the hardware PWM module of the Microchip PIC microcontroller to generate
a PWM waveform of the given frequency and duty cycle. Once this command
is called, the PWM will be emitted until PWMOff is called.

`_channel_` is 6 or 7, and corresponds to the PMW6 or PMW6
respectively.

`_frequency_` sets the frequency of the PWM output. It is measured in KHz.
The maximum value allowed is 255 KHz. The minimum value varies depending
on the clock speed. 1 KHz is the minimum on chips 16 MHz or under and 2
Khz is the lowest possible on 20 MHz chips. In situations that do not
require a specific PWM frequency, the PWM frequency should equal
approximately 1 five-hundredth the clock speed of the microcontroller (ie 40 Khz on
a 20 MHz chip, 16 KHz on an 8 MHz chip). This gives the best duty cycle
resolution possible.

`_duty cycle_` specifies the desired duty cycle of the PWM signal, and
ranges from 0 to 255 where 255 is 100% duty cycle.

`_timer_` specifies the desired to be used. These can be timer 2, 4 or 6.


*Example:*
----
    'This program will alter the brightness of an LED using
    'hardware PWM.

    'Select chip model and speed
    #chip 16F18855, 32

    'Set the PWM pin to output mode
    DIR PORTA.2 out

    'Main code
    do
        'Turn up brightness over 2.5 seconds
        For Bright = 1 to 255
            HPWM 6, 40, Bright, 2
            wait 25 ms
        next
        'Turn down brightness over 2.5 seconds
        For Bright = 255 to 1
            HPWM 6, 40, Bright, 2
            wait 25 ms
        next
    loop
----
*For more help, see* <<_pwmoff,PWMOff>>
