==== InitTimer7

*Syntax:*
[subs="quotes"]
----
InitTimer7 _source_, _prescaler_
----
*Command Availability:*

Available on  Microchip microcontrollers with a Timer 7 module.

*Explanation:*

`InitTimer7` will set up timer 7.

Parameters are required as detailed in the table below:

[cols=2, options="header,autowidth"]

|===

|Parameter
|Description

|`_source_`
|The clock source for this specific timer. Can be either `Osc`, `Ext` or `ExtOsc` where: +
`Osc` is an internal oscillator. +
`Ext` is an external oscillator. +
`ExtOsc` is an external oscillator and only available on a Microchip PIC microcontroller.

|`_prescaler_`
|The value of the prescaler for this specific timer.  See the tables below for permitted vales for Microchip PIC or the Atmel AVR microcontrollers.

|===

When the timer overflows an interrupt event will be generated.
This interrupt event can be used in conjunction with `On Interrupt` to run a section of code when the interrupt event occurs.
{empty} +
{empty} +
{empty} +
{empty} +
*Microchip PIC microcontrollers:*

On Microchip PIC microcontrollers `_prescaler_` must be one of the following constants:

[cols="^1,1,^1", options="header,autowidth"]
|===
|*Prescaler Value*
|*Primary GCB Constant*
|*Constant Equates +
to value*

|1:1
|`PS7_1`
|0

|1:2
|`PS7_2`
|16

|1:4
|`PS7_4`
|32

|1:8
|`PS7_8`
|48

|===

These correspond to a prescaler of between 1:2 and 1:8 of the oscillator (FOSC/4)
speed. The prescaler will apply to either the oscillator or the external
clock input.
{empty} +
{empty} +
{empty} +
{empty} +


*Supported in <TIMER.H>*
